//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int buildingID { get; set; }
        public string buildingName { get; set; }
        public int parkID { get; set; }
    
        public virtual Park Park { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
