//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Park
    {
        public Park()
        {
            this.Buildings = new HashSet<Building>();
        }
    
        public int parkID { get; set; }
        public string parkName { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual Park Park1 { get; set; }
        public virtual Park Park2 { get; set; }
    }
}
