//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int preferencesID { get; set; }
        public int userID { get; set; }
        public int period { get; set; }
        public int hr24Format { get; set; }
        public string defaultLocation { get; set; }
        public string defaultPage { get; set; }
        public string header1 { get; set; }
        public string header2 { get; set; }
        public string header3 { get; set; }
    
        public virtual User User { get; set; }
    }
}
