//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Rooms = new HashSet<Room>();
            this.Rooms1 = new HashSet<Room>();
            this.Facilities = new HashSet<Facility>();
        }
    
        public int requestID { get; set; }
        public string moduleCode { get; set; }
        public string status { get; set; }
        public int weekID { get; set; }
        public string day { get; set; }
        public int periodStart { get; set; }
        public int periodEnd { get; set; }
        public int semester { get; set; }
        public int year { get; set; }
        public int round { get; set; }
    
        public virtual Week Week { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Room> Rooms1 { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
    }
}
